stages:
  - pdflatex

buildpdf:
  image: gitlab-registry.cern.ch/giordano/chep2016-bmkclouds
  stage: pdflatex
  script:
    - cd $CI_PROJECT_DIR
    - pdflatex -interaction=nonstopmode kv_performance.tex ; bibtex kv_performance ; pdflatex -interaction=nonstopmode kv_performance.tex
  allow_failure: true  
  artifacts:
    paths:
      - $CI_PROJECT_DIR 
    expire_in: '1 day'
    when: always
