stages:
  - pdflatex

buildpdf:
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:latex-cc7 
  stage: pdflatex
  script:
    - cd $CI_PROJECT_DIR
    - pdflatex -interaction=nonstopmode kv_performance.tex ; bibtex kv_performance ; pdflatex -interaction=nonstopmode kv_performance.tex
    
  artifacts:
    paths:
      - $CI_PROJECT_DIR 
